services:
  api:
    build: .
    container_name: encurtador-go
    env_file: api/.env
    restart: unless-stopped
    networks:
      - homelab
    labels:
      logging: "promtail"
      service: "encurtador"

networks:
  homelab:
    external: true
